### ISSUE TITLE
Update Description guidelines

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#14]
- https://uhlibraries-digital.github.io/bcdams-map/#description
- https://uhlibraries-digital.github.io/bcdams-map/guidelines/description

**Comment by librarycard** [comment]
Can description be repeatable?

**Comment by metaweidner** [comment]
It's listed as repeatable in the DPLA MAP, so we could change it to repeatable. What is the use case for having multiple descriptions?

**Comment by librarycard** [comment]
For instance, if there's a caption or inscription that's now being mapped to the description field

**Comment by metaweidner** [comment]
@librarycard  I see captions and inscriptions as being folded into the text of the Description field, perhaps identified by a construction such as `Inscription on back: "inscription text"`. That's the easiest path, and many of the Inscription and Caption fields in the UHDL legacy data already employ that construction for ease of migration. It seems like you're suggesting typed Description instances as in Description.content, Description.caption, Description.inscription, etc. Is that correct?

**Comment by metaweidner** [comment]
Better to map Inscriptions and Captions to Description than Note.

**Comment by dulekde** [comment]
I found UNT's entry on content description very helpful http://www.library.unt.edu/digital-projects-unit/quick-start-metadata-guide#description-content-description

**Comment by amgaynor** [comment]
If the title is the same as the description, do we need to repeat it in the description?

**Comment by metaweidner** [comment]
We should aim to keep the metadata as DRY as possible. Description should be used to add value to the metadata. It's OK to omit the Description field if it's only repeating what's recorded elsewhere.

**Comment by amgaynor** [comment]
@librarycard I can't remember, were you going to add any guidelines for preservation?

**Comment by amgaynor** [comment]
We talked about this a little bit at the Data Migration Working group. We're wondering if we should differentiate the components of the `Description` field in any particular way since it may include caption and inscriptions. In the Medieval Manuscripts collection different description section headings appear in all caps, e.g. 

`Ms. text includes: Proper of Season, Christmastide, Office at Matins, First and second nocturn. LAYOUT: 2 columns, ruled in lead, very faded (118 x 82 mm). Leroy 00D2, written in 31 lines below top line. SCRIPT: Gothic textualis.`

So for us it might look something like this:

`CAPTION on front: "Billy Jurges, a former big league shortstop, talking to infielder Sonny Jackson during a break for lunch at Apache Junction, Ariz., training camp."`

It does visually differentiate it which could be helpful, but I don't know that I love it. It would be great to get some other feedback on this.

Also, regarding translations of captions or inscriptions, perhaps we could use this construction? (with/without all caps based on our decision):
`Caption below:  "Antonio I. Villarreal candidato a senador." Caption below (English translation): "Antonio I. Villareal candidate for senator."`

**Comment by amgaynor** [comment]
@lisacruces thanks for getting these notes from SC: 

> So many different kinds of standards could be applied. I’d say that would be preferable to apply an existing rule than to create a new one.

>[DCRM(B)](http://rbms.info/files/dcrm/dcrmb/DCRMB3.pdf) 7A2. Punctuation says that one should “Start a new paragraph for each note. End each paragraph with a period or other mark of final punctuation….Separate introductory wording from the main content of a note by a colon followed by not preceded by a space.” DCRM(B) does not say to capitalize the introductory wording.

>[DCRM(G)](http://rbms.info/files/dcrm/dcrmg/DCRMG.pdf) appears to follow the same guidelines. I think there is other good guidance in there, too. Like 7B5.2. Picture captions, etc. “When the pictorial element of a single resource with text has a distinctive caption independent of the chosen title, give it in a note with an appropriate introductory word or phrase, if considered important.” Example “Picture caption: General view of the twelve colossal water proof canvas pavilions…”

**Comment by amgaynor** [comment]
Given this feedback, I'm inclined to say that captions and inscriptions will be recorded in the description field, but will not be differentiated by all caps. Unless there's any other feedback on this, I'll also just go with the translation construction I mention above. 

Examples of `Description` field: 

- `Caption on front: "Billy Jurges, a former big league shortstop, talking to infielder Sonny Jackson during a break for lunch at Apache Junction, Ariz., training camp."`
- `Caption below:  "Antonio I. Villarreal candidato a senador." Caption below (English translation): "Antonio I. Villareal candidate for senator."`
- `Postcard of Blanche E. Chenoweth posing with two other women wearing hats. Inscription on front: "October 14, 1910." Inscription on back: "Blanche E. Chenoweth middle. Boy oh boy! What hats!"`
