### ISSUE TITLE
Consolidate DPTF & DAMSTF Wiki Pages

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/bcdams-map#50]
As we discussed today, let's create one wiki page that includes the Metadata Dictionary mappings for the entire BCDAMS-MAP, currently split into DPTF & DAMSTF.

**Comment by amgaynor** [comment]
I took a first pass at consolidating them here: https://github.com/uhlibraries-digital/bcdams-map/wiki/04-UHDL-Crosswalk

I need to look a little more closely to make sure I caught everything. In particular, I'm wondering if, for Time Period, we want to use Temporal Coverage from the DPLA MAP.

**Comment by amgaynor** [comment]
Thanks for reworking the page, Andy. A few notes: 

1. We do have a Note field in UHDL, but I see that it's not on the current metadata dictionary page. I added it to the Crosswalk page. I'll add it to the current metadata dictionary page.

2. I added the exceptions from the KUHT Highlights collection 

3. Should the bf:series property be [bf:hasSeries](http://id.loc.gov/ontologies/bibframe.html#p_hasSeries)? I don't see bf:series in the [BIBFRAME 2.0 Vocab List](http://id.loc.gov/ontologies/bibframe.html). 

Otherwise, I think it's ready to go.

**Comment by metaweidner** [comment]
@amgaynor As we discussed this morning, please create another page that lists all elements in the MAP for DMWG use. I'll close this issue when scheduling the next meeting.

**Comment by amgaynor** [comment]
@metaweidner I've created the page here: https://github.com/uhlibraries-digital/bcdams-map/wiki/05-BCDAMS-Field-Set

Take a look at let me know if it's missing anything at this point.

**Comment by metaweidner** [comment]
Looks good @amgaynor. I will distribute this to the DMWG.
